spring:
  datasource:
    url: jdbc:h2:file:./pizzadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
    com:
      bcopstein: DEBUG
application:
  name: ex4-lancheriaddd-v1
precos:
  estrategia-imposto: taxa-fixa
  estrategia-desconto: fidelidade
  taxa-imposto: 0.10
  percentual-desconto-fidelidade: 0.07
  minimo-pedidos-fidelidade: 3
  janela-dias-fidelidade: 20
server:
  port: 8080